name: jungle_themed_quiz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/jungle_quiz1.jpeg
    - assets/images/jungle_background2.jpeg
  fonts:
    - family: JungleFont
      fonts:
        - asset: assets/fonts/TropicJungle.ttf
